package com.joshuacerdenia.android.easynotepad.data.database

import androidx.lifecycle.LiveData
import androidx.room.*
import com.joshuacerdenia.android.easynotepad.data.Note
import java.util.*

@Dao
interface NoteDao {

    @Query("SELECT * FROM note")
    fun getNotes(): LiveData<List<Note>>

    @Query("SELECT * FROM note WHERE id=(:id)")
    fun getNote(id: UUID): LiveData<Note?>

    @Update // no params; SQL command generated by Room
    fun updateNote(note: Note)

    @Insert // same as above
    fun addNote(note: Note)

    @Delete // same, I guess??
    fun deleteNote(note: Note)
}